### ISSUE TITLE
Reminder for EuroLLVM 2020

### ISSUE THREAD

**Issue by bhack** [llvm/mlir-www#10]
This is just a reminder to add slides refernce from EuroLLVM cause it is full of (Google members) MLIR talks :wink: http://llvm.org/devmtg/2020-04/talks.html

**Comment by joker-eph** [comment]
We'll do! 
(I don't think we'll get to add this before the conference though)

**Comment by jpienaar** [comment]
I think we can close this now given EuroLLVM is cancelled, but perhaps we could move the talks that would have happened to the open design meeting.

**Comment by bhack** [comment]
@jpienaar Yes. Better than nothing.
