### ISSUE TITLE
image file is not shown at https://mlir.llvm.org/docs

### ISSUE THREAD

**Issue by kiszk** [llvm/mlir-www#16]
We cannot see an image (near the words "Index Map Example") at https://mlir.llvm.org/docs/LangRef/ while it is referred to as `![Index Map Example](includes/img/index-map.svg)` in https://github.com/llvm/llvm-project/blob/master/mlir/docs/LangRef.md.

As far as I know, the files under `mlir/docs/includes` are not copied in these files.
https://github.com/llvm/mlir-www/blob/master/copy_docs.sh
https://github.com/llvm/mlir-www/blob/master/.github/workflows/main.yml

**Comment by jpienaar** [comment]
You are correct and thanks for flagging this.

**Comment by jpienaar** [comment]
Updated to fix (here and in llvm repo).

**Comment by kiszk** [comment]
Now, we can see the image file. Thanks!
