### ISSUE TITLE
[docs][mlir]Duplicated -DCMAKE_BUILD_TYPE=Release in MLIR Windows Build Instructions 

### ISSUE THREAD

**Issue by aabhinavg1** [llvm/mlir-www#201]
# Duplicated `-DCMAKE_BUILD_TYPE=Release` in MLIR Windows Build Instructions

In the [MLIR Getting Started guide](https://mlir.llvm.org/getting_started/), under the Windows compile/testing section, the CMake command includes a duplicated `-DCMAKE_BUILD_TYPE=Release` flag:

```bash
cmake ..\llvm -G "Visual Studio 15 2017 Win64" -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="Native" -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
```
#Proposed Fix
```bash
cmake ..\llvm -G "Visual Studio 15 2017 Win64" -DLLVM_ENABLE_PROJECTS=mlir -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="Native" -Thost=x64 -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON
```

**Comment by aabhinavg1** [comment]
https://github.com/llvm/mlir-www/pull/202
this pull wll fix the issue

**Comment by aabhinavg1** [comment]
@rengolin, could you please review this pull request? Your feedback would be greatly appreciated!

**Comment by aabhinavg1** [comment]
Hi @joker-eph,

I have create the pull request to fix the duplicated **CMAKE_BUILD_TYPE** in the **Windows** build instructions which have been approved. However, we currently don’t have write access to merge it. Could you please merge it for us?

Additionally, could you provide some guidance on how we might obtain write access in the future?

Thank you!

**Comment by rengolin** [comment]
> Additionally, could you provide some guidance on how we might obtain write access in the future?

https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access

Though this process is changing at the moment, it still applies until the document changes.

**Comment by aabhinavg1** [comment]
Thank you for reviewing the pull request! I appreciate the guidance on the process for obtaining commit access. It’s helpful to know how contributions are currently managed for the website. If there's anything else needed from my side, please let me know!

**Comment by rengolin** [comment]
> > https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access
> 
> This isn't applicable to the website though, we're in general taking pull-requests and having a maintainer merge PRs for the website right now.

Good point!
